# Action on push
name: Build - itunes-connect-slack

on: 
  push:
    branches:
      - master
      - main

jobs:
  push_to_registry:
    name: Build & upload to GitHub registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build & Push to registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.ORG_PERSONAL_ACCESS_TOKEN }}
          registry: docker.pkg.github.com
          repository: jnqa/itunes-connect-slack/ics
          tags: latest
      - name: Tag new version
        uses: pkgdeps/action-package-version-to-git-tag@v1
        with:
          github_token: ${{ secrets.ORG_PERSONAL_ACCESS_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"